### ISSUE TITLE
No MPN for 1.8V regulator on PDF schematic

### ISSUE THREAD

**Issue by cHemingway** [sparkfun/SparkFun_Edge#2]
The 1.8V regulator, U3, does not have a part number written next to it.

I was interested to know what it was to estimate the power consumption, as it is always powered, though with disabled output by default.

**Comment by nseidle** [comment]
Np. AP2127K-1.8TRG1. [Datasheet](https://www.diodes.com/assets/Datasheets/AP2127.pdf). Quiescent current looks to be 60µA.

**Comment by cHemingway** [comment]
Thanks!
